<a href="https://colab.research.google.com/github/nidbhagat/Early_Python/blob/main/Numpy_PostRead2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Content

- **Creating special arrays**
    - `zeros()`
    - `ones()`
    - `diag()`
    - `identity()`

- **Numpy based Mathematical functions**

    - **Absolute values**
        - `np.absolute()`
        - `np.abs()`

    - **Trigonometric Functions**
        - `np.sin()`, `np.cos()`
        
    - **Exponential and Logarithmic Functions**
        - `np.exp()`, `np.log()`, `np.log2()`, `np.log10()`


In [1]:
import numpy as np

#Creating special arrays using Numpy
How will create numpy array with all zeros?

In [5]:
a = np.zeros(4)
# 4 signifies the numbers of zeros in an array
a

array([0., 0., 0., 0.])

In [6]:
a.dtype # data type of the above array is a float

dtype('float64')

####Can also create 2D array, by pass in shape (as tuple)

In [8]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

#### How will you create numpy array with all ones?

In [9]:
np.ones(3)

array([1., 1., 1.])

In [11]:
# 2D
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

#### Now, do we need `np.twos()`, `np.threes()`, `np.fours()`, .... `np.hundreds()`?

- **NO**

- We can just create array using `np.ones()` and **multiply** with **required value**

In [12]:
np.ones((3,3))*4

array([[4., 4., 4.],
       [4., 4., 4.],
       [4., 4., 4.]])

#### One more frequently appearing arrays are **diagional** **matrices**

In [13]:
np.diag([1,2,3,4])
# we pass values for diagonal elements as a list, all other elements are zero

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [14]:
np.diag([2,5,7])

array([[2, 0, 0],
       [0, 5, 0],
       [0, 0, 7]])

#### How will you create identity matrix?

First of all, what are identity matrices

- It's a **square matrix**
- Where **all diagonal values are 1**
- **All non-diagonal values are 0**

In [18]:
x = np.diag([1,1,1])
# However, we have a function called identity() to create identity matrix, only difference is the dtype
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [19]:
x.dtype

dtype('int64')

In [20]:
y = np.identity(3)
y

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
y.dtype

dtype('float64')

## Numpy Mathematical functions

### Absolute values

At times, we might need to find absolute values of elements in array. Numpy provides a very easy-to-use function for this purpose



#### `np.absolute()`

It calculate the absolute value element-wise. It returns an ndarray containing the absolute value of each element.

In [22]:
x = np.array([-1.2, 1.2, -2])
np.absolute(x)

array([1.2, 1.2, 2. ])

If the input is a complex value, like `x = a + ib`, the absolute value is $\sqrt(a^2 + b^2)$. This is a scalar if x is a scalar.

In [25]:
np.absolute(2+1j)

2.23606797749979

#### `np.abs()`
The `abs` function can be used as a shorthand for `np.absolute` on ndarrays.

### Trigonometric Functions

In addition to arithmetic expressions using operators, Numpy provides functions for element-wise evaluation of many elementary trigonometric functions and operations.


Each of these functions takes a single array (of arbitrary dimension) as input and returns a new array of the same shape, where for each element the function has been applied to the corresponding element in the input array.

### `np.sin()`, `np.cos()`

This function takes only one argument and is used to compute the sine function for all values in the array:

In [26]:
x = np.linspace(-1,1,11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [30]:
y = np.sin(np.pi*x)
y

array([-1.22464680e-16, -5.87785252e-01, -9.51056516e-01, -9.51056516e-01,
       -5.87785252e-01,  0.00000000e+00,  5.87785252e-01,  9.51056516e-01,
        9.51056516e-01,  5.87785252e-01,  1.22464680e-16])

In [33]:
np.round(y,decimals=3)

array([-0.   , -0.588, -0.951, -0.951, -0.588,  0.   ,  0.588,  0.951,
        0.951,  0.588,  0.   ])

Here we also used the **constant** `np.pi` and the function `np.round()` to round the values of `y` to three decimals.


Like the `np.sin` function, many of the elementary trigonometric math functions take one input array and produce one output array. We can also make these functions operate on two input arrays and return one array:

#### For example: $\sin^2x + \cos^2x = 1$

In [34]:
np.add(np.sin(x)**2, np.cos(x)**2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [35]:
np.sin(x)**2 + np.cos(x)**2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Exponential and Logarithmic Functions

#### `np.exp()`

This function returns element-wise exponent raised to power of element's value

In [36]:
x = np.arange(0,3)
x

array([0, 1, 2])

In [37]:
np.exp(x) # returns e**0, e**1, e**2

array([1.        , 2.71828183, 7.3890561 ])

#### `np.log()`, `np.log2()`, `np.log10()`

These functions return Logarithms of base e, 2, and 10, respectively.

In [42]:
x = np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [44]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

***
