<a href="https://colab.research.google.com/github/nidbhagat/Early_Python/blob/main/class_project/Airbnb_NPS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 11.1MB/s]


In [8]:
score = np.loadtxt('survey.txt',dtype='int')

In [9]:
score

array([ 7, 10,  5, ...,  5,  9, 10])

In [10]:
score.ndim

1

In [11]:
score.shape

(1167,)

In [12]:
score.min()

1

In [13]:
score.max()

10

In [14]:
score.mean()

7.250214224507284

#NPS = %promoters - %detractors

In [15]:
promoters = score[score>=9].shape[0]
detractors = score[score<=6].shape[0]
total = score.shape[0]

In [16]:
per_prom = promoters/total * 100
per_detra = detractors/total * 100

In [17]:
NPS = per_prom - per_detra
NPS

23.73607540702657

#round() func

In [18]:
np.round(NPS,2)

23.74



---



# np.empty() func
#### built-in function, helps to create the **empty array**



---



---



#Categorial solution to calculate NPS

In [45]:
arr = np.empty(shape=score.shape,dtype='str')

In [46]:
arr

array(['', '', '', ..., '', '', ''], dtype='<U1')

In [26]:
arr[0]='Hello'

In [27]:
arr # index 0 has 'H' only because of the data type (i.e. type is only 1 character; U1)

array(['H', '', '', ..., '', '', ''], dtype='<U1')

#Assigning of value to the empty array
####the length of the value storing in the index depends on the data type.
#### let change the U1 -> U6 and again store **Hello** to 0th index.

In [47]:
arr=arr.astype('U10')

In [22]:
arr[0]='Hello'

In [23]:
arr

array(['Hello', '', '', ..., '', '', ''], dtype='<U6')

In [48]:
arr[score<=6] = 'Detractors'

In [49]:
arr

array(['', '', 'Detractors', ..., 'Detractors', '', ''], dtype='<U10')

In [50]:
arr[score>=9] = 'Promotors'
arr

array(['', 'Promotors', 'Detractors', ..., 'Detractors', 'Promotors',
       'Promotors'], dtype='<U10')

In [51]:
arr[(score>=7) & (score<=8)] = 'Passive'
arr

array(['Passive', 'Promotors', 'Detractors', ..., 'Detractors',
       'Promotors', 'Promotors'], dtype='<U10')

In [56]:
detractors_count = arr[arr=='Detractors'].shape[0]
promoters_count = arr[arr=='Promotors'].shape[0]

# np.unique() func
#### Returns the sorted unique elements of an array.
#### 3 optional outputs in addition to the unique elements:


```
# unique(ar, return_index=False, return_inverse=False, return_counts=False,
axis=None)
```
unique_elements - give all the unique elements
indices - index of the unique elements
inverse_indices - reconstruct the original array
counts - total counts of each unique elements



In [59]:
np.unique(arr)

array(['Detractors', 'Passive', 'Promotors'], dtype='<U10')

In [62]:
unique_elements, indices, inverse_indices, counts = np.unique(arr, return_index=True, return_inverse=True, return_counts=True,
axis=None)

In [63]:
unique_elements, indices, inverse_indices, counts

(array(['Detractors', 'Passive', 'Promotors'], dtype='<U10'),
 array([2, 0, 1]),
 array([1, 2, 0, ..., 0, 2, 2]),
 array([332, 226, 609]))

In [64]:
arr[inverse_indices] # helps to reconstruct the original input array

array(['Promotors', 'Detractors', 'Passive', ..., 'Passive', 'Detractors',
       'Detractors'], dtype='<U10')

In [75]:
per_detractors = counts[0]/counts.sum() * 100
per_detractors

28.449014567266495

In [74]:
per_promotors = counts[2]/counts.sum() * 100
per_promotors

52.185089974293064

In [77]:
NPS = per_promotors - per_detractors
NPS

23.73607540702657